version: '3.1'

services:

  adminer:
    image: adminer:4.7.1-standalone
    restart: always
    ports:
      - 8090:8080

  db:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - "./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/"
